name: Health Check

on:
  schedule:
    - cron:  '25,35 * * 12 *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Good Health PING
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://blooming-woodland-46628.herokuapp.com/health
          retry-all: no
      - name: Bad Health PING
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://blooming-woodland-46628.herokuapp.com/bad-health
          retry-all: no