name: Health Check

on:
  schedule:
    - cron:  '15 8 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Good Health PING
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://blooming-woodland-46628.herokuapp.com/health